name: Deploy
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      API_BASE_URL: https://sandbox-partners-api.airalo.com
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npm run test:api
  deploy:
    runs-on: ubuntu-latest
    needs: test # This job depends on the test job to be finised
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: echo "Building project..."
      
      - name: Deploy
        run: echo "Deploying to production..."
